# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @academic/shared-types build",
  "pnpm --filter @academic/api-client build", 
  "pnpm --filter @academic/backend build"
]

[start]
cmd = "cd apps/backend && pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3001"
